name             'install_docker_container'
maintainer       'Thomas Mayrhofer'
maintainer_email 'thomas@mayhrofer.at'
license          'All rights reserved'
description      'Installs/Configures install_docker_container'
version          '0.1.0'
